import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="antialiased h-full">
        <header className="w-full bg-emerald-950 p-2 text-center absolute top-0">
          <Link href="/" className="font-bold text-2xl">
            GoA2 Your Happy Place
          </Link>
        </header>
        <div className="p-8 h-full flex flex-col justify-center">
          {children}
        </div>
      </body>
    </html>
  );
}
